Add: Enemy will surrender when city becomes free
Vdauphin/HeartsAndMinds pull request #1020
Opened 2021-01-08 08:00 UTC by GoldJohnKing

(Use English only.)

- Add: Enemy will surrender when city becomes free (@GoldJohnKing).

**When merged this pull request will:**
- If enemy amount is less than (3 + random 3), city will becomes free and remaining enemies will surrender.
- If unit is a UAV, it will be destroyed immediately.
- If unit is inside vehicle, it will dismount then surrender.
- If unit is on foot, it will surrender.
- Also added setTriggerInterval to decrease trigger check interval (default 0.5s now 15s), it may slightly improve performance.
- I'm new on coding, and the code seems not that gentle than I thought, so this might need to be carefully reviewed.

**Final test:**
- [ ] local
- [ ] server

**Screenshots**

2021-01-08 10:15 UTC, Vdauphin requested changes
I really dislike this because it make useless to talk to civilian to find last enemies

This must be optionnal like this: 
Auto free cities when number of enemies is lower than:
- 0
- 1
- 2
- 3

2021-01-08 11:49 UTC, GoldJohnKing commented
> I really dislike this because it make useless to talk to civilian to find last enemies

Yes, I agree with you, however AI sometimes stuck inside rock or solid buildings, and bomb UAV sometimes run out of fuel and land inside grass... I used to talk to civilian to obtain information about enemy position, however they prefer to lie in most cases, even we have a high reputation. (I've read #1021, so this might be a bug?) Besides,  It's rather difficult for players to find those enemies, this is rather desperate for players as they make all efforts but to find this mission too difficult to be achieve.

> This must be optional like this:
> Auto free cities when number of enemies is lower than:
> 
> * 0
> * 1
> * 2
> * 3

Yes, I agree, I will do that.

2021-01-08 12:33 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +} forEach (_city getVariable ["data_units", []]);
My fault... All I can come up with now is:

1. Use allUnits to get all units
2. Use select or inAreaArray to get units inside city radius

This could be... a mess. Would you please suggest an approach to obtain all units assigned to current city?

2021-01-08 13:21 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +} forEach (_city getVariable ["data_units", []]);
It is exactly what I would do!

2021-01-08 13:39 UTC, Vdauphin commented
>  agree with you, however AI sometimes stuck inside rock 

This should not happen: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/findPos.sqf#L45

> or solid buildings, 

Never notice glitch, may be I play too much on vanilla

>  however they prefer to lie in most cases, even we have a high reputation. 

This should not happen if reputation is above 1200 I think.
But under it may be fake or not: https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf#L61

> It's rather difficult for players to find those enemies, this is rather frustrating to players as they make all efforts but to find this mission too difficult to be achieve.

This fix just make sure we get the closer enemy. Personally I feel AI really magnetize by player

2021-01-08 13:51 UTC, GoldJohnKing commented
Hi, I've pushed a new commit, would you please check if it solves issues about above conversations?

2021-01-08 14:05 UTC, Vdauphin reviewed
Looks cool now

2021-01-08 14:20 UTC, GoldJohnKing commented
Okay, this should be okay.

2021-01-08 16:19 UTC, GoldJohnKing commented
I'm really confused. I tried to use the same method as `btc_fnc_side_capture_officer` has used to make vehicle crew get out of the vehicle and surrender, but it just won't work...

https://github.com/Vdauphin/HeartsAndMinds/blob/5e15500ab030956569a21d615b21ccb771c6d705/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf#L128

May be we can ignore those units inside vehicles or static weapons from surrendering?

2021-01-08 17:26 UTC, Vdauphin commented
> make vehicle crew get out of the vehicle and surrender

This code doesn't order crew to get out

2021-01-09 02:36 UTC, GoldJohnKing commented
I remember the officer in `btc_fnc_side_capture_officer` side-mission would automatically disembark from its vehicle and surrender if player is nearby, which only uses `doStop _captive; [_captive, true] call ace_captives_fnc_setSurrendered;`. I wonder why it doesn't work this time...

2021-01-09 02:42 UTC, GoldJohnKing commented
Another problem:

I see arguments of `unassignVehicle` and `doGetOut` are local, so what about those remote units on headless client, such as enemy patrols passing the city?

2021-01-09 08:22 UTC, GoldJohnKing commented
Hi, I've done most of the works that I can come up with. It works now, though seems to be quite a ugly approach. It's time to review and optimize the code if possible.

> > agree with you, however AI sometimes stuck inside rock
> 
> This should not happen: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/findPos.sqf#L45
> 
> > or solid buildings,
> 
> Never notice glitch, may be I play too much on vanilla

Bad news, this happens just on vanilla with only latest stable ace and cba loaded.

![Arma3_x64 2021-01-09 16-06-42](https://user-images.githubusercontent.com/26923626/104086909-aca50500-5296-11eb-977e-cf4d4b739478.png)

![Arma3_x64 2021-01-09 16-06-48](https://user-images.githubusercontent.com/26923626/104086925-c7777980-5296-11eb-89ae-d9e03028d3ef.jpg)

![Arma3_x64 2021-01-09 16-07-01](https://user-images.githubusercontent.com/26923626/104086920-baf32100-5296-11eb-9940-69afdc1834c9.png)

2021-01-09 09:49 UTC, Vdauphin commented
> I remember the officer in btc_fnc_side_capture_officer side-mission would automatically disembark from its vehicle and surrender if player is nearby,

This is just an AI behavior. When AI see enemies they just getout for the fight

> which only uses doStop _captive; [_captive, true] call ace_captives_fnc_setSurrendered;. I wonder why it doesn't work this time...

There is nothing asking AI to getout of vehicle here.


> Bad news, this happens just on vanilla with only latest stable ace and cba loaded.

Please don't offtopic, make an issue with step

2021-01-09 10:02 UTC, Vdauphin requested changes

2021-01-09 10:18 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +if !(_remainEnemyUnits isEqualTo []) then {
Nope, this is just to make sure if `_remainEnemyUnits` is empty to avoid execution on empty string. Settings off is handled in the trigger's condition statement, in mission.sqf. (I don't know how to quote the code itself in pr...)

```
private _p_city_free_trigger = "btc_p_city_free_trigger" call BIS_fnc_getParamValue;
btc_p_city_free_trigger_condition = if (_p_city_free_trigger isEqualTo 0) then {
    "thisList isEqualTo = []" // This handles condition if setting is off
```

2021-01-09 10:39 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +if !(_remainEnemyUnits isEqualTo []) then {
You are right, I won't do that check
and remove the useless line:
`    private _cfgVehicles = configFile >> "CfgVehicles";`

2021-01-09 10:54 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +if !(_remainEnemyUnits isEqualTo []) then {
Done.

2021-01-14 17:09 UTC, Vdauphin requested changes
From my point of view, the AI should not surrender if there are inside a heli or vehicle. It doesn't really make sense

2021-01-15 03:23 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +        if (getNumber (configOf _vehicle >> "isUav") isEqualTo 1) then {
I remember this file already use `unitIsUAV`. Have you pulled the branch before review?

> From my point of view, the AI should not surrender if there are inside a heli or vehicle. It doesn't really make sense

I agree, this need further discussion.

2021-01-21 02:34 UTC, GoldJohnKing commented
@Vdauphin Sorry for late reply, I'm pretty busy these days... 😅💦

We need to discuss if remaining infantries should surrender while the city has at least one vehicle (including LandVehicle, Air and Ship).

Here are some situations I can come up with:

1. Infantries should surrender while city will be free, however vehicles should continue fighting.
2. Infantries should not surrender while city will not be free, until remaining vehicles are destroyed or leave the city.
3. Only with LandVehicle inside the city, infantries should not surrender while city will not be free, until those LandVehicles are destroyed or leave the city, Ship or Air vehicle inside the city neither surrender nor prevent city from becoming free.

Which one do you prefer? If you have a better plan, please enlighten me and I'll give it a try.

2021-01-21 02:50 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +                _remainEnemyUnits = _remainEnemyUnits - crew _vehicle;
Should be resolved by vehicle surrender behavior refactor (6b8a116).

2021-01-21 02:50 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
> +                    _remainEnemyUnits = _remainEnemyUnits - _crew;
Should be resolved by vehicle surrender behavior refactor (6b8a116).

2021-01-21 09:10 UTC, Vdauphin commented
> 2. Infantries should not surrender while city will not be free, until remaining vehicles are destroyed or leave the city.

This one

2021-01-21 09:47 UTC, GoldJohnKing commented
> > 1. Infantries should not surrender while city will not be free, until remaining vehicles are destroyed or leave the city.
> 
> This one

What about UAV? There are always UAV run out of fuel and land in the grass, making it difficult for players to find and destroy it to free the city.

2021-01-21 10:00 UTC, Vdauphin commented
> > > 1. Infantries should not surrender while city will not be free, until remaining vehicles are destroyed or leave the city.
> > 
> > 
> > This one
> 
> What about UAV? There are always UAV run out of fuel and land in the grass, making it difficult for players to find and destroy it to free the city.

Exclude them from the search

2021-01-21 13:42 UTC, GoldJohnKing commented
Changed as requested, please review.
I also added units in `StaticWeapon` to surrender list, because sometimes static weapons are spawned inside "solid"/non-enterable buildings.

2021-01-21 17:44 UTC, Vdauphin commented
You exclude UAV because those are not AI. It is a problem due to the Arma implementation.
For static weapon, it doesn't make sense.

> because sometimes static weapons may spawned inside "solid"/non-enterable buildings.

Your pull request is to make AI surrender when there are just a few of them. So this is out of the scope of this pull request.
Make a FIX for this issue instead.

2021-01-22 01:39 UTC, GoldJohnKing commented
> Your pull request is to make AI surrender when there are just a few of them. So this is out of the scope of this pull request.
> Make a FIX for this issue instead.

My pull request aims at providing a workaround, which should avoid the issue that buggy AI could prevent a city from becoming free, such as unit inside rock or stuck in building, and UAV out of fuel stay silently in the grass. There are so many circumstances which might cause the issue, so make those remaining enemy surrender is the most effective way of making player less frustrated during the process.

In a word, surrender is just a method, solving the issue is the purpose.

2021-01-22 08:52 UTC, Vdauphin commented
> > Your pull request is to make AI surrender when there are just a few of them. So this is out of the scope of this pull request.
> > Make a FIX for this issue instead.
> 
> My pull request aims at providing a workaround, which should avoid the issue that buggy AI could prevent a city from becoming free, such as unit inside rock or stuck in building, and UAV out of fuel stay silently in the grass. There are so many circumstances which might cause the issue, so make those remaining enemy surrender is the most effective way of making player less frustrated during the process. So this pull request includes infantry, static weapon, and UAV, while does not include other types of vehicle, because vehicle can move and is much more easier to be found. It's more like a fail-safe, instead of a complete new feature.
> 
> In a word, surrender is just a method, solving the issue is the purpose. That's why I think these should be included in the same pr.

Sorry, I do not accept a workaround for those issue. I only accept fix for issue. If those issue exist please make a ticket. I don't know if you notice but all issue here are resolved by taking the time to understand why they appear. And when there are carefully understood, a fix is provided.

2021-01-22 09:24 UTC, GoldJohnKing commented
Ok, I get it.

2021-01-22 09:30 UTC, GoldJohnKing commented
Changed as requested, please review.

2021-01-25 21:18 UTC, Vdauphin requested changes

2021-01-25 21:18 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> +    format ["if (count thisList > %1) exitWith {false}; private _return = true; private _veh; {_veh = vehicle _x; if !(_veh isKindOf 'Man' || {unitIsUAV _veh}) exitWith {_return = false;};} forEach t
```
if (count thisList > %1) exitWith {false};
thisList findIf {
    private _veh = vehicle _x;
    !(
        _veh isKindOf 'Man' ||
        {unitIsUAV _veh}
    )
} isEqualTo -1
```
This looks more readable if it is inside a file under city folder.

2021-01-26 02:07 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> +    format ["if (count thisList > %1) exitWith {false}; private _return = true; private _veh; {_veh = vehicle _x; if !(_veh isKindOf 'Man' || {unitIsUAV _veh}) exitWith {_return = false;};} forEach t
Okay, working in progress...

2021-01-26 05:37 UTC, GoldJohnKing commented on =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> +    format ["if (count thisList > %1) exitWith {false}; private _return = true; private _veh; {_veh = vehicle _x; if !(_veh isKindOf 'Man' || {unitIsUAV _veh}) exitWith {_return = false;};} forEach t
> ```
> if (count thisList > %1) exitWith {false};
> thisList findIf {
>     private _veh = vehicle _x;
>     !(
>         _veh isKindOf 'Man' ||
>         {unitIsUAV _veh}
>     )
> } isEqualTo -1
> ```

I wonder if this would have impact on performance.

In my code, once a vehicle is found, it will exit immediately:
```
{
        _veh = vehicle _x;
        if !(_veh isKindOf 'Man' || {unitIsUAV _veh}) exitWith { // Exit immediately once a vehicle is found
            _return = false;
        };
    } forEach _remainEnemyUnits;
```

This might save some CPU time, because it's no need to go through the whole array.

2021-01-26 09:48 UTC, Vdauphin approved these changes
Perfect! Good job!

2021-02-26 10:25 UTC, merged