FIX: Updating french translation
Vdauphin/HeartsAndMinds pull request #1581
Opened 2024-02-08 18:35 UTC by Omega974

FIX: Updating french translation
When merged this pull request will:

Update the translation
https://github.com/Vdauphin/HeartsAndMinds/issues/400

**Final test:**
- [ ] local
- [ ] server

**Screenshots**

2024-02-09 22:46 UTC, Vdauphin requested changes
Thank you very much for the help, some stuff still need to be fix

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Nombre de ticket que rapporte un prissonier (Activé cette option seulement si les tickets ne sont pas partagés): </French>
```suggestion
                <French>Nombre de ticket que rapporte un prisonier (Activé cette option seulement si les tickets ne sont pas partagés): </French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Tous les joueurs sont connectés</French>
```suggestion
                <French>A tous les joueurs connectés</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Le joueur interagissant avec le point logistique</French>
```suggestion
                <French>Au joueur interagissant avec le point logistique</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Le joueur connecté à un solde de 0 ticket</French>
```suggestion
                <French>Au joueur connecté avec un solde de 0 ticket</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Le joueur avec le plus faible solde de ticket (0 inclus)</French>
```suggestion
                <French>Au joueur avec le plus faible solde de ticket (0 inclus)</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Les slot sont partagés entre tous les joueurs</French>
```suggestion
                <French>Les slots sont partagés entre tous les joueurs</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Tremblement De Visée</French>
```suggestion
                <French>Tremblement de visée</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Vitesse De Visée</French>
```suggestion
                <French>Vitesse de visée</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Distance De Repérage</French>
```suggestion
                <French>Distance de repérage</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Temps De Détection</French>
```suggestion
                <French>Temps de détection</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Vitesse De Rechargement</French>
```suggestion
                <French>Vitesse de rechargement</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Sur les véhicule et le team leader</French>
```suggestion
                <French>Sur les véhicules et le team leader</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Copié l'enventaire</French>
```suggestion
                <French>Copier l'enventaire</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Collé l'inventaire</French>
```suggestion
                <French>Coller l'inventaire</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Restoré l'inventaire</French>
```suggestion
                <French>Restorer l'inventaire</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Forcer la porte</French>
```suggestion
                <French>Forcer la serrure</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Aucun joueur n'as besoin de ticket</French>
```suggestion
                <French>Aucun joueur n'a besoin de ticket</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>L'inventaire n'as pas été copier</French>
```suggestion
                <French>L'inventaire n'a pas été copié</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Pas d'objet dans les environ!</French>
```suggestion
                <French>Pas d'objet dans les environs !</French>
```

2024-02-09 22:46 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Réarmement éffectué.</French>
```suggestion
                <French>Réarmement effectué.</French>
```

2024-02-10 20:00 UTC, Omega974 commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Copié l'enventaire</French>
"inventaire"

2024-02-10 22:36 UTC, Vdauphin requested changes
Thanks again!
Still some change

2024-02-10 22:36 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Densité du renseignements dans les maisons:</French>
```suggestion
                <French>Densité du renseignements dans les maisons :</French>
```

2024-02-10 22:36 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Nombre de ticket perdu par mort:</French>
```suggestion
                <French>Nombre de ticket perdu par mort :</French>
```

2024-02-10 22:36 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Nombre de ticket que rapporte un prisonier (Activer cette option seulement si les tickets ne sont pas partagés): </French>
```suggestion
                <French>Nombre de ticket que rapporte un prisonier (Activer cette option seulement si les tickets ne sont pas partagés) : </French>
```

2024-02-10 22:36 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Copier l'enventaire</French>
```suggestion
                <French>Copier l'inventaire</French>
```

2024-02-10 22:40 UTC, Vdauphin approved these changes
Perfect!

2024-02-10 22:41 UTC, Omega974 commented
> Perfect!

Like you !

2024-02-10 22:52 UTC, merged