Add: Side Mission Improvements
Vdauphin/HeartsAndMinds pull request #1633
Opened 2024-07-29 13:49 UTC by mrschick

- Add: Side Mission Improvements (@mrschick).

**When merged this pull request will:**
- In the "Capture Officer in Convoy" Mission, fix the Officer not disembarking his vehicle once surrendered.\
Previously, if the officer's vehicle was not disabled (leading to him disembarking) before "surrendering" him, it would become almost impossible to get him out of the vehicle safely.\
Now, he will disembark by himself, regardless of vehicle health, before surrendering.
- In the "Rescue Heli Pilot" Mission, fix the Pilot being "found" immediately after mission creation.\
This was being caused by the pilot activating his own "found" trigger, which looks for units of the player side <20m from the pilot, being turned non-captive and then often being killed by nearby enemy units, before players had a chance to clear the area first.\
I fixed this by changing the "unfound" pilot's side to civilian, as he is later switched to the player side anyway when joining the group of the players who found him.
- In the Assassination and Hostage Rescue Missions:
  - Do not place the task on the exact position of the unit to kill/rescue, instead place it nearby, so that the house in which the officer/hostage is located is within a 50m "Area of Uncertainty", displayed around the task (re-uses supply mission "area" marker, see images below).
  - After placing the Officer/Hostage on a random position in the building, if that position is "outside" (often porch or roof), cycle through available positions again for one that is "inside" to place the Officer/Hostage in. Then place guarding units in all other positions.
  - Do not use small buildings with less than 4 positions for Assassination missions.

**Final test:**
- [x] local
- [x] server

**Screenshots**

"Area of Uncertainty" for Hostage/Assassination Missions:
![new-task-aou](https://github.com/user-attachments/assets/4f0adc93-0d3d-47a8-a17d-6f62c63bbe32)

2024-07-31 16:28 UTC, Vdauphin requested changes
A little mixed here, I let you see my comments

2024-07-31 17:02 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
It is an issue on our Takistan mission, playing as Takistani Army against "3CB: Takistan Insurgents", with a Mi-8 (Cargo) as the only respawnable heli.
It generates a 3CB Takistan Armed Forces pilot as the captive, but immediately completes the "find him" task. I presume it's because he activates his own trigger since he's of the player side (INDFOR), and setting him to civilian fixed it.
Maybe it's something else, I don't recall encountering the issue on our previous mission, where we played as (vanilla) AAF vs FIA.

2024-07-31 17:03 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
> +[_taskID, 15, _taskPosition, [_city getVariable "name", _civType]] call btc_task_fnc_create;
You mean they can share the task's location?
Is there an alternative for not visualizing the task right on the officer/hostage?

2024-07-31 17:10 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
> +    _trigger setTriggerStatements ["this", format ["_captive = thisTrigger getVariable 'captive'; deleteVehicle thisTrigger; moveOut _captive; doStop _captive; [_captive, true] call ace_captives_fnc_
I did mainly encounter it while testing, where I can just TP close to the vehicle, but iirc it also happened while playing, possibly by getting close before having damaged the vehicle, blocking him inside.

2024-07-31 18:11 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
> +    _trigger setTriggerStatements ["this", format ["_captive = thisTrigger getVariable 'captive'; deleteVehicle thisTrigger; moveOut _captive; doStop _captive; [_captive, true] call ace_captives_fnc_
Yeah, just confirmed it. If you get close to his vehicle and trigger the surrender before having him disembark, you'll have to disable the vehicle, then he will run around and you will have to chase him down to handcuff him.

2024-08-01 17:37 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
> +[_taskID, 15, _taskPosition, [_city getVariable "name", _civType]] call btc_task_fnc_create;
> You mean they can share the task's location?

Side mission are supposed to be intel from civilian, so there are supposed to be accurate
Also, this allows players to carefully plan how to attack

H&M already includes many "inaccurate" intel/task, as example when you spawn for the first time you literally have no "visible" objective labelled on the map, which is pretty unique and disruptive. In the opposite, side mission are here to help player lost which out goal. They give a clear objective to them

2024-08-01 17:38 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
Thanks for the info, I will check this weekend

2024-08-01 18:16 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
> +[_taskID, 15, _taskPosition, [_city getVariable "name", _civType]] call btc_task_fnc_create;
Ah, understood, makes sense.
I guess the exact position of the officer/hostage within the house should still be hidden though, maybe by centering the task on the building's position.

2024-08-03 07:47 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
Still working with the Mi-8
[=BTC=co@30_Hearts_and_Minds.Altis.zip](https://github.com/user-attachments/files/16478588/BTC.co%4030_Hearts_and_Minds.Altis.zip)
![20240803094532_1](https://github.com/user-attachments/assets/7421fb65-d5bc-496a-b1da-f4a3ae6eb766)

2024-08-03 07:49 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
> +[_taskID, 15, _taskPosition, [_city getVariable "name", _civType]] call btc_task_fnc_create;
I disagree, I see many people failing the mission even with this exact position by killing the hostage for example
Also, the gameplay here is not to find the target but save the hostage by releasing him without killing him or triggering the random mine  
For officer, is to manage to bring the dog tag back to base, not actually killing the officer

2024-08-03 09:13 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
Alright, finally figured it out, KJW Imposters is the one causing the issue by removing the captive state immediately, leading to the trigger to activate.
I'll look into it to determine whether the compatibility can be done by the mod or this mission.

2024-08-03 09:25 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
> +[_taskID, 15, _taskPosition, [_city getVariable "name", _civType]] call btc_task_fnc_create;
> failing the mission even with this exact position by killing the hostage
IMHO, that's just a skill-issue of being overly aggressive and not "surgical" enough with the available weapons 🤷🏻‍♂️

For the others, IMO not knowing the exact position leads to more fun by having to realistically plan a CQB assault without knowing where exactly the objective is.

Anyway, I'll revert those commits.

2024-08-06 12:37 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
I added a unit flag to KJW Imposters to prevent resetting of its captive state, in case of conflicts with a mission script. 
https://github.com/Vdauphin/HeartsAndMinds/pull/1633/commits/83d1c901dc6a32e57447cec4809da6986023aa6a will add usage of that flag to the Heli Pilot, as soon as it is deployed with the next KJW Imposters update (probably next monday).

2024-08-06 16:58 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
I feel like KJW Imposters should simply not change the captive state when already in captive mode
Would work with any other mission/mod that set this state

2024-08-06 23:53 UTC, mrschick commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> +private _group = createGroup civilian;
Can't think of a simple way to do that, since it has to manipulate captive state directly.

2024-08-10 09:41 UTC, Vdauphin approved these changes
Thanks!

2024-08-11 15:58 UTC, merged