Tom draal adv chem
Vdauphin/HeartsAndMinds pull request #1674
Opened 2024-12-01 18:41 UTC by TomDraal

Hi,
I've made some changes in order to add some more advanced settings on the Chemical Warfare in H&M.
The idea is to enable chemical warfare and choose if the chemical side missions will spawn or not and also set a chance probability of having a chemical weapons cache or not.

- Add: advanced settings on chemical warfare (@TomDraal).

**When merged this pull request will:**
- Allow the user to choose if he/she wants to have chemical side missions while chemical warfare is enabled
- Tweak the chance probability (%age) of having a chemical weapons cache

**Final test:**
- [X] local
- [X] server

2024-12-01 21:33 UTC, Vdauphin commented
Hello,

Thank you for your contribution
We need to be consistent between setting
Before: `btc_p_chem` ON, side mission and chemical were enabled
Now, if `btc_p_chem` ON but `btc_p_chem_sides` and `btc_p_chem_cache_probability` are OFF, nothing will happen

Despite, I don't really see the point of having a setting for side mission as they can be skipped by the Officer I would recommend to 
- add the existing setting `btc_p_chem`: Off, On without weapon cache, On without side mission, On with both
- create a `btc_p_chem_cache_probability` as you did without the 0%

Cheers

2024-12-03 18:23 UTC, TomDraal commented
Hello,
We want to be able to deactivate the chemical side missions because sometimes while using the skip feature some contaminated elements remains. At least we had some bad surprises in the past, so deactivating the chemical side missions is the safest way.
If you want full consistency then the best way is to completely remove `btc_p_chem` which I saw like a general switch on / off.
So I wanted to keep it just in case someone would want to add other chemical warfare related tasks.
By only keeping `btc_p_chem_sides` and `btc_p_chem_cache_probability` with a 0-100% range, we will have the behaviour you described : 
- sides ON and cache OFF (0%)
- sides OFF and cache ON (>0%)
- sides OFF and cache OFF (0%) => equivalent to btc_p_chem OFF
- sides ON and cache ON (>0%) => equivalent to btc_p_chem ON
Would that suits you ?
Cheers

2024-12-05 17:50 UTC, Vdauphin commented
> If you want full consistency then the best way is to completely remove btc_p_chem which I saw like a general switch on / off.

I thought about it but I think it would be simpler to use number instead of bool for `btc_p_chem` (just do  `btc_p_chem > 0` where needed)
It is up to you to make a choice on this!

2024-12-15 18:52 UTC, Vdauphin requested changes
thanks for the update, some suggestion her

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
> +    ["_p_chem", (btc_p_chem_cache_probability > 0), [true]],
```suggestion
    ["_p_chem", btc_p_chem_cache_probability > 0, [true]],
```

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
> +    class btc_p_chem_sides { // Advanced Chemical warfare setting to activate / deactivate chemical side missions
```suggestion
    class btc_p_chem_sides { // Toggle chemical side missions:
```

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
> +    class btc_p_chem_cache_probability { // Advanced Chemical warfare setting to change probability of a chemical weapon cache
```suggestion
    class btc_p_chem_cache_probability { // Chemical weapon cache probability:
```

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf
> +private _isChem = (btc_p_chem_sides || (btc_p_chem_cache_probability > 0));
One line:

```sqf
if !(btc_p_chem_sides || (btc_p_chem_cache_probability > 0)) exitWith {};
```

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/handleShower.sqf
> +private _isChem = (btc_p_chem_sides || (btc_p_chem_cache_probability > 0));
One line and no extra parenthesis

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
> +[_cache_pos, (btc_p_chem_cache_probability > 0), [1, 0] select _isChem] call btc_cache_fnc_create;
```suggestion
[_cache_pos, btc_p_chem_cache_probability > 0, [1, 0] select _isChem] call btc_cache_fnc_create;
```

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
> +[_cache_pos, (btc_p_chem_cache_probability > 0), [1, 0] select _isChem] call btc_cache_fnc_create;
```suggestion
[_cache_pos, btc_p_chem_cache_probability > 0, [1, 0] select _isChem] call btc_cache_fnc_create;
```

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
> +private _isChem = (btc_p_chem_sides || (btc_p_chem_cache_probability > 0));
one line

2024-12-15 18:52 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
> +private _isChem = (btc_p_chem_sides || (btc_p_chem_cache_probability > 0));
one line

2024-12-17 21:22 UTC, Vdauphin requested changes
Some tiny change!

2024-12-17 21:22 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Probabilité de cache d'armes chimique:</French>
```suggestion
                <French>Probabilité de cache d'armes chimiques :</French>
```

2024-12-17 21:22 UTC, Vdauphin commented on =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> +                <French>Missions secondaires chimiques:</French>
```suggestion
                <French>Missions secondaires chimiques :</French>
```

2024-12-18 19:45 UTC, Vdauphin approved these changes

2024-12-19 19:46 UTC, merged